server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
bank.uri = http://localhost:8080/payments
logging.level.root=INFO

# Tracing
management.tracing.sampling.probability=1.0


# Log pattern with traceId and spanId
logging.pattern.console=%d{HH:mm:ss} [%thread] [traceId=%X{traceId} spanId=%X{spanId}] %-5level %logger{36} - %msg%n
